### PR TITLE
Binary Tree Right Side View

### PR DESCRIPTION
**Pull request by harshita9621**
Example:
Input: root = [1,2,3,null,5,null,4]
Output: [1,3,4]

### CODE REVIEW

**Comment by harshita9621** [comment]
@mihir0699 Review this PR

**Review by mihir0699 — APPROVED** [review]

**Comment by mihir0699** [comment]
Thanks a lot for the contribution @harshita9621 , keep going 🎉

**Comment by harshita9621** [comment]
@mihir0699 It showing mature in 14 days

**Comment by mihir0699** [comment]
> @mihir0699 It showing mature in 14 days

Yes every PR take 14 days to mature in Hacktoberfest

**Comment by harshita9621** [comment]
@mihir0699  Then the fest get end

**Comment by mihir0699** [comment]
> @mihir0699 Then the fest get end

It can mature even after the fest ends, no worries

**Comment by harshita9621** [comment]
@mihir0699 Today the fest get end .kindly mature my PR

**Comment by mihir0699** [comment]
> @mihir0699 Today the fest get end .kindly mature my PR

I don't have the access to mature the PR, it will get matured automatically

**Pull request merged**
